version: 0.0.1.{build}
pull_requests:
  do_not_increment_build_number: true
image:
- Visual Studio 2017
- Visual Studio 2017 Preview
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: dotnet restore
build:
  parallel: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: dtdKRChf20EyrxeGeMgNxa2847UCfg0GTazdFR3rge+avmfue97QDREoaoXCSXI2
  skip_symbols: false
  artifact: /.*\.nupkg/