name: qodana-scan

on:
    push:
    pull_request:

jobs:
    qodana-scan:
        name: Qodana Scan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Qodana scan
              uses: JetBrains/qodana-action@main
              with:
                  upload-result: true
                  args: --baseline,qodana.sarif.json
              env:
                  QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
